apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-user-service.fullname" . }}-config
  labels:
    {{- include "wasp-user-service.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  dbHost: {{ include "wasp-user-service.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
  authServiceHost: {{ .Values.config.authServiceHost }}
  authServicePort: {{ .Values.config.authServicePort | quote }}
  authServiceApiVersion: {{ .Values.config.authServiceApiVersion }}
  authTokenName: {{ .Values.config.authTokenName }}
  authTokenExpiryDays: {{ .Values.config.authTokenExpiryDays | quote }}
  {{ if .Values.config.init.adminPassword.enabled -}}
  initAdminLogLevel: {{ .Values.config.init.adminPassword.logLevel }}
  {{- end }}
